### PR TITLE
Windows CI

### PR DESCRIPTION
**Pull request by eric-unc**
Adding Windows CI

### CODE REVIEW

**Comment by ac-freeman** [comment]
Next time only make the PR once you think it's all good on your fork. Just keeps things cleaner on the repo

**Comment by eric-unc** [comment]
Fair ig but CI was did appear to be triggered without the PR

**Comment by ac-freeman** [comment]
You have to create an Action on your own fork

**Comment by eric-unc** [comment]
Should I add Windows CI to the disabled workflows? @ac-freeman 

I'm a bit curious why they're disabled...

**Comment by ac-freeman** [comment]
Not sure what you mean

**Comment by eric-unc** [comment]
This only modifies the [rust_action_test_and_docs.yml](https://github.com/ac-freeman/adder-codec-rs/blob/main/.github/workflows/rust_action_test_and_docs.yml) workflow. Should I modify the other two? It seems that they are disabled ([[1]](https://github.com/ac-freeman/adder-codec-rs/actions/workflows/adder_info.yml), [[2]](https://github.com/ac-freeman/adder-codec-rs/actions/workflows/codec_crate_action_opencv.yml)).

**Comment by ac-freeman** [comment]
Those are old, just ignore them

**Comment by eric-unc** [comment]
In that case you can merge this, or let me know if there's a better way to clean it up. I'm not sure which branch you want the bandwidth limiting to be in but please rebase that one if it isn't the main branch so I can work on that next.

**Pull request merged**
